language: python
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "nightly"
install:
  - pip install -r requirements.txt
script:
  - black module_tracker tests --check
  - flake8 module_tracker
  - isort -rc -c module_tracker tests
  - python -m pytest
  - codecov
